id = "toon"
name = "TOON"
version = "0.0.2"
schema_version = 1
authors = ["Shawn Yu <yyuxiaoran@qq.com>"]
description = "TOON support."
repository = "https://github.com/3swordman/zed-toon"

[grammars.toon]
repository = "https://github.com/3swordman/tree-sitter-toon"
rev = "fc3d478797d51f0bc3c9a5b7773a727ec6eb64f4"
