id = "toon"
name = "TOON"
version = "0.0.1"
schema_version = 1
authors = ["Shawn Yu <yyuxiaoran@qq.com>"]
description = "TOON support."
repository = "https://github.com/3swordman/zed-toon"

[grammars.toon]
repository = "https://github.com/3swordman/tree-sitter-toon"
rev = "0292e1316c3588539d616aad235a7d8f4b524374"
